name: Build and Publish

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Build and Test
        run: |
          pip install .
          pytest

  publish-to-pypi:
    if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v') }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: install publication tools
        run: |
          pip install twine wheel
          pip install .
      - name: publish-to-pypi
        run: scripts/publish.sh
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

  tag-release:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          persist-credentials: false
      - name: Tag a release
        uses: twosixlabs-dart/dart-tag-release@v3.0.34
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          release_version: ${{ format('3.1.{0}', github.run_number) }}
